// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0eaoaOBXT5dGgWeXyPQM9-iWesS2XwQ',
    appId: '1:283790230715:web:6ff6dc50f84b32bb81959e',
    messagingSenderId: '283790230715',
    projectId: 'project-app-3e2ee',
    authDomain: 'project-app-3e2ee.firebaseapp.com',
    storageBucket: 'project-app-3e2ee.appspot.com',
    measurementId: 'G-E5KK74WJ3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV_KNtHOfleDc4cmiXULoaA177VZqlTzA',
    appId: '1:283790230715:android:fec5d07006779bda81959e',
    messagingSenderId: '283790230715',
    projectId: 'project-app-3e2ee',
    storageBucket: 'project-app-3e2ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTP0TmhB8ovO_ggHbr39_Q2fxE1n7q2M',
    appId: '1:283790230715:ios:519945209d5929d881959e',
    messagingSenderId: '283790230715',
    projectId: 'project-app-3e2ee',
    storageBucket: 'project-app-3e2ee.appspot.com',
    iosClientId: '283790230715-7cnbfri8od4ak6bj36jctkrkrfhs4807.apps.googleusercontent.com',
    iosBundleId: 'com.example.grProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTP0TmhB8ovO_ggHbr39_Q2fxE1n7q2M',
    appId: '1:283790230715:ios:41357d578cb478ca81959e',
    messagingSenderId: '283790230715',
    projectId: 'project-app-3e2ee',
    storageBucket: 'project-app-3e2ee.appspot.com',
    iosClientId: '283790230715-b0h8joknlh5560g1vamu54h99n4ro94d.apps.googleusercontent.com',
    iosBundleId: 'com.example.grProject.RunnerTests',
  );
}
